# app custom Makefile

# Docker repo & image name without version
IMAGE     ?= ghcr.io/umami-software/umami

# Docker image version
IMAGE_VER ?= postgresql-v2.1.0

# Hostname for external access
APP_SITE  ?= umami.dev.lan
# App names (db/user name etc)
APP_NAME  ?= umami

# Enable DB usage:
# * Add DB config part to .env.sample
# * Enable db* targets
# * make db-create inside .drone-default target
USE_DB    ?= yes

# ------------------------------------------------------------------------------
# app custom config

APP_SECRET  ?= $(shell < /dev/urandom tr -dc A-Za-z0-9 | head -c32; echo)

# ------------------------------------------------------------------------------
# .env template (custom part)
# inserted in .env.sample via 'make config'
define CONFIG_CUSTOM
# ------------------------------------------------------------------------------
# app custom config, generated by make config
# db:$(USE_DB) user:$(ADD_USER)

APP_SECRET=$(APP_SECRET)

endef

# ------------------------------------------------------------------------------
# Find and include DCAPE/apps/drone/dcape-app/Makefile
DCAPE_COMPOSE   ?= dcape-compose
DCAPE_MAKEFILE  ?= $(shell docker inspect -f "{{.Config.Labels.dcape_app_makefile}}" $(DCAPE_COMPOSE))
ifeq ($(shell test -e $(DCAPE_MAKEFILE) && echo -n yes),yes)
  include $(DCAPE_MAKEFILE)
else
  include /opt/dcape-app/Makefile
endif

# -----------------------------------------------------------------------------
## Custom app targets
#:
